attachments:
  replace_original: False           # Replace original attachment if there is one
  inject_new: True                 # If there are no attachments, inject a new one?
  path: /tmp/Phishing/documentation.pdf.zip  # Path to the attachment to inject
  attachment_message: "<h2>Use the password 'documentation' to access the contents of the attached zip</h2>"
links:
  all: https://www.bing.com/search?q=a+bird # Evilginx Phishing Lure
  #shl.com: https://www.bing.com/search?q=an+elephant 
  #office.com: https://www.bing.com/search?q=a+squirrel
  #google.com: https://www.bing.com/search?q=a+zebra 
tracking_url: "https://yourtrackingpixeldomain.com/"
unc_path: "\\\\<YOUR IP>\\images\\xxxxx.png"